title: "Neladri Roy"
description: "My professional online resume"
baseurl: "/resume"        # the subpath of your site, e.g. /resume
url: ""
theme: minima      # lightweight Jekyll theme
plugins:
  - jekyll-feed
